<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\STOW.Engine\STOW.Engine.csproj" />
    <ProjectReference Include="..\STOW.Platform.Windows\STOW.Platform.Windows.csproj" />
    <ProjectReference Include="..\STOW.Infrastructure\STOW.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\LICENSE" LogicalName="STOW.Legal.STOW_LICENSE.txt" />
    <EmbeddedResource Include="..\..\PRIVACY.md" LogicalName="STOW.Legal.PRIVACY.md" />
    <EmbeddedResource Include="..\..\THIRD_PARTY_NOTICES.md" LogicalName="STOW.Legal.THIRD_PARTY_NOTICES.md" />
    <EmbeddedResource Include="..\..\CREDITS.md" LogicalName="STOW.Legal.CREDITS.md" />
    <EmbeddedResource Include="GeneratedLegal\*.*">
      <LogicalName>STOW.Legal.%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AssemblyName>STOW</AssemblyName>
    <RootNamespace>STOW.App</RootNamespace>
    <Version>0.4.0-preview.5</Version>
    <AssemblyVersion>0.4.0.0</AssemblyVersion>
    <FileVersion>0.4.0.0</FileVersion>
    <Description>A calmer desktop starts here.</Description>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
